# Generated by Django 4.1.5 on 2023-02-19 03:08

from django.db import migrations

from seedling.climate.sensor import is_anomalous


def update_readings(apps, _):
    ClimateReading = apps.get_model('climate', 'ClimateReading')
    for reading in ClimateReading.objects.all():
        reading.anomalous = is_anomalous(reading.percent_humidity, reading.degrees_celsius)
        reading.save()


class Migration(migrations.Migration):

    dependencies = [
        ("climate", "0002_add_is_anomalous_field"),
    ]

    operations = [
        migrations.RunPython(update_readings),
    ]
