# Generated by Django 4.1.5 on 2024-01-18 04:41

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        unique=True,
                        verbose_name="created",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        height_field="height_px",
                        upload_to="images//%Y/%m/%d/",
                        width_field="width_px",
                    ),
                ),
                ("height_px", models.IntegerField()),
                ("width_px", models.IntegerField()),
            ],
        ),
    ]
