# Generated by Django 4.1.5 on 2024-01-18 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imaging", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(
                height_field="height_px", upload_to="images/", width_field="width_px"
            ),
        ),
    ]
